### ISSUE TITLE
Trying to display multiple slides, scroll by one slide only

### ISSUE THREAD

**Issue by rickibarnes** [davidcetinkaya/embla-carousel#14]
I can use CSS to quickly change Embla so that instead of showing a single slide, it shows more (e.g. `width:25%`), however when using `scrollNext` and `scrollPrev`, it still scrolls by 100%, for the full number of slides. 

This means that for several clicks on next/prev button, there are no slides showing. I really like Embla and don't want to have to implement a different solution, but I have no idea where to even start changing the TS to make it perform as expected. Do you have any plans to update to allow the functionality I'm after?

**Comment by davidcetinkaya** [comment]
Hello @rickibarnes,
Thanks for reporting this issue 👍🏻!

I’m not quite sure I understand. Are you changing the slide widths **dynamically** with CSS?

Would you mind forking this [CodeSandbox](https://codesandbox.io/s/embla-carousel-loop-false-oyols) to create an example that demonstrates the issue?

Thank you in advance!
David

**Comment by rickibarnes** [comment]
Hey thanks for replying so quickly. That sandbox you've set up works perfectly when I do what I'm trying to do in my own code, so obviously it's something about how I've got things set up. 

I suspect it's because I'm doing it manually, not through node or yarn or anything. I've found it's quite hard (for me) to convert the examples to how I need it.

**Comment by davidcetinkaya** [comment]
Hi @rickibarnes,

No worries, I’m happy if I can help you solve this 👍🏻.

It should work the same even if you inject the script manually with a `<script>` tag. Maybe you can compare the **HTML setup** and how it’s done in that Sandbox example i sent you?

Or you could create a separate CodeSandbox with only your code, so I can debug what’s going on 🙂?

**Comment by rickibarnes** [comment]
I'm having a bit of trouble doing any of those things. I know this is a noob question, but when making a CodeSandbox, how do I include the script manually? I tried copy/paste into a new script file, but that gave me a million linting problems and my embla wouldn't work.

**Comment by davidcetinkaya** [comment]
@rickibarnes, I understand 👍.
I'll help you get started. I'm at work right now but I'll get to it as soon as possible. I'll let you know when I've set up an example you can work with to demonstrate the issue.

**Comment by davidcetinkaya** [comment]
Hello @rickibarnes,

I've setup a [CodePen here](https://codepen.io/DavidCetinkaya/pen/jjGYgx) where you should be able to add your own code. As you can see in the `HTML` column I've included the `<script>` tag for you.

When you're done, just hit the `Save` button at the top and copy the `url` in the browser adressbar, and send it to me here. That way I can debug what's going on and hopefully pinpoint the issue 🙂.

**Comment by rickibarnes** [comment]
Thanks mate, I really appreciate how responsive you are on this. I've [forked that Pen](https://codepen.io/rickibarnes/pen/zVPYVP), but frustratingly I'm not able to replicate the error. This little example works exactly as I would want it to, with the exception of a strange overlap on the last of the thumbnails (you can see it with the border on).

Funnily enough, at one point yesterday, my broken page was working exactly the same as this Pen. I refreshed the page and it's back to being broken again. I can only assume it's something else interfering with it, but I don't know that I'll be able to work out what it is.

**Comment by davidcetinkaya** [comment]
No worries, I'm glad if I'm helping 🙂. Hmm, very strange that it doesn't seem consistent 😕 .

So I looked at the `CodePen` I got from you and I saw an issue with how you add space between the slides. Margin was applied directly to the slide elements, but the **recommended way** of adding space between slides is as follows:

```html
<div class="embla__container">
  <div class="embla__slide">
    <div class="embla__slide__inner">
      <!-- your content -->
    </div>
  </div>
</div>
```

```css
.embla__container {
  display: flex;
  will-change: transform;

  /* Choose desired spacing between slides and subtract it from container */
  margin-left: -14px;
}

/* The .embla__slide class should only have following CSS properties */
.embla__slide {
  position: relative; /* Needed for the loop effect to work */
  flex: 0 0 auto; /* Make sure the slide takes up the space it needs */
  width: 25%; /* Choose desired width */

  /* Choose desired spacing between slides and match it with the subtracted space from container */
  padding-left: 14px; 
}

/* The .embla__slide__inner class can be styled however you like */
.embla__slide__inner {
  border: 1px solid red;
  /* Choose any desired styles */
}
```

Please take a look at the [modified CodePen](https://codepen.io/DavidCetinkaya/pen/OeOVgO) here. The strange overlap should be gone.

Maybe this helps?
