### ISSUE TITLE
Incorrect position of the last slide for { align: 'start', loop: true }

### ISSUE THREAD

**Issue by ludik1** [davidcetinkaya/embla-carousel#275]
### Bug is related to

- [X] embla-carousel (core package)
- [ ] embla-carousel-react
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation website)

### Embla Carousel version

- v4.2.1

### Describe the bug
For the option:
emblaOptions = { align: 'start', loop: true };
If you are on the first slide, the last slide is not visible on the left side(check attached image).

### CodeSandbox
https://codesandbox.io/s/embla-carousel-loop-vanilla-forked-cvdnu?file=/src/js/index.js

### Steps to reproduce
After init, there is no slide on the left.

### Expected behavior
The last slide will be visible on the left side for the loop option.

### Additional context
Correct:
<img width="717" alt="Screenshot 2022-01-28 at 13 34 03" src="https://user-images.githubusercontent.com/9254388/151548665-be616e6e-a18e-40bc-96c0-a62084584e65.png">
Incorrect:
<img width="720" alt="Screenshot 2022-01-28 at 13 32 01" src="https://user-images.githubusercontent.com/9254388/151548674-dd1bc7ee-34b0-446e-8d69-caf91cdac3ff.png">

**Comment by davidcetinkaya** [comment]
Hi @ludik1,

This is because you shouldn't move your container element directly:

```css
.embla__container {
  display: flex;
  user-select: none;
  -webkit-touch-callout: none;
  -khtml-user-select: none;
  -webkit-tap-highlight-color: transparent;
  left: 50px; /* why this? */
  position: relative;
}
```

Additionally, please add the following CSS: `margin-left: -10px` on your container class like so:

```css
.embla__container {
  display: flex;
  user-select: none;
  -webkit-touch-callout: none;
  -khtml-user-select: none;
  -webkit-tap-highlight-color: transparent;
  margin-left: 10px; /* Add this to account for slide paddings */
  position: relative;
}
```

This is not a bug.

Kindly,
David
