### ISSUE TITLE
Changing options through CSS doesn't seem to work

### ISSUE THREAD

**Issue by th-km** [davidcetinkaya/embla-carousel#302]
### Bug is related to

embla-carousel-react

### Embla Carousel version

v6.2.0

### Describe the bug

Changing Embla options through CSS doesn't seem to work. Both VSCode and CodeSandbox flag the CSS as "non-valid", and the pseudo options part breaks the CSS layout.

### CodeSandbox

https://codesandbox.io/s/embla-carousel-default-react-forked-4qptzn?file=/src/css/embla.css

### Steps to reproduce

1. Follow the CodeSandbox
2. See how the CSS breaks and how the options are not picked

### Expected behavior

Embla should be able to pick options defined in your CSS file as mentioned [here](https://www.embla-carousel.com/guides/breakpoints/#changing-options)

**Comment by davidcetinkaya** [comment]
Hi @th-km,

I think you need to make sure the JSON string is on one line for the CSS parser to parse it correctly. Try this:

```css
.embla__viewport:before {
  display: none;
  content: '{ "draggable": false, "loop": true }'; /* <--- put it on one line */
}
```

Best,
David
