### ISSUE TITLE
Example of using multiple slides and making it responsive

### ISSUE THREAD

**Issue by dmorda** [davidcetinkaya/embla-carousel#40]
Hi David,

I noticed that in 2.4.0 you introduced the containScroll option, which allows me to use that in combination with slidesToScroll to display multiple slides at once. I was wondering if you had any recommendations on how to make the carousel responsive when used in this way.

For example, I want to show a different number of slides depending on the size of the window...
* Desktop: slidesToScroll: 3
* Tablet: slidesToScroll: 2
* Phone: slidesToScroll: 1

One idea I had was to detect changes to the windows size and then fire the changeOptions() method to update the slidesToScroll option.

Is that the right approach, or would you recommend something else?

**Comment by davidcetinkaya** [comment]
Hello Damon (@dmorda),
Thank you for your question. Regarding:

> Allows me to use that in combination with slidesToScroll to **display multiple slides at once**.

If it's only about displaying multiple slides at once in the carousel viewport, you can achieve this with CSS only. Because Embla listens for the window resize event and will update accordingly if you change the slide widths. Assuming you have the flexbox setup like the [quickstart](https://github.com/davidcetinkaya/embla-carousel#quickstart) example, here's how to do it:

```css
/* Mobile - 1 slide in viewport */
.embla__slide {
  flex: 0 0 100%;
}

/* Tablet - 2 slides in viewport */
@media (min-width: 768px) {
  .embla__slide {
    flex: 0 0 50%;
  }
}

/* Desktop - 3 slides in viewport */
@media (min-width: 992px) {
  .embla__slide {
    flex: 0 0 33.3333%;
  }
}
``` 

But if you also want to change any of the Embla [options](https://github.com/davidcetinkaya/embla-carousel#options) like [`slidesToScroll`](https://github.com/davidcetinkaya/embla-carousel#slidestoscroll) or [`containScroll`](https://github.com/davidcetinkaya/embla-carousel#containscroll), the way to do it is as you say calling `changeOptions()`. One way to do this is to listen for the Embla resize event like so:

```javascript
embla.on('resize', () => {
  /*
  - Check current breakpoint
  - Determine how many slides to scroll for this breakpoint
  - Store it in a variable called slidesToScroll
  - Update Embla options
  */
  embla.changeOptions({ slidesToScroll });
});
```

Let me know if this helps!

Best,
David
